package dev.heyduk.relay.domain.model

enum class RelayMessageType { STATUS, RESPONSE, PERMISSION, QUESTION, COMPLETION, TEXT, TRANSCRIPT, DIRECTORY_LIST, SESSION_CREATED, LAST_RESPONSE, AUTH_REQUIRED, AUTH_URL, AUTH_TIMEOUT }
